<?php

namespace AppBundle\Repository;

/**
 * AlibapassGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlibapassGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
