<?php

namespace AppBundle\Repository;

/**
 * EntryFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
