<?php

namespace AppBundle\Repository;

/**
 * FirewallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirewallRepository extends \Doctrine\ORM\EntityRepository
{
}
