<?php

namespace AppBundle\Repository;

/**
 * LostCredentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostCredentialRepository extends \Doctrine\ORM\EntityRepository
{
}
