root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /entries
        permanent: true
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
login:
    path: /login
    defaults: { _controller: AppBundle:Login:login }
entries:
    path: /entries
    defaults: { _controller: AppBundle:Entries:entries }